before_script:
  - echo "$HKU_USERNAME" > ".env"
  - echo "$HKU_PASSWORD" > ".env"
  - echo "$MONGODB_USERNAME" > ".env"
  - echo "$MONGODB_PASSWORD" > ".env"
  - echo "$MONGODB_URI" > ".env"
  - echo "$DB" > ".env"
  - cat ".env"

include:
  - template: AWS/Deploy-ECS.gitlab-ci.yml